
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('group_member').del(),

    // Inserts seed entries
    knex('group_member').insert({id: 1,
      group_id: 1,
      member_id: 1}),
    knex('group_member').insert({id: 2,
      group_id: 1,
      member_id: 2}),
    knex('group_member').insert({id: 3,
      group_id: 1,
      member_id: 3}),
    knex('group_member').insert({id: 4,
      group_id: 1,
      member_id: 4}),
    knex('group_member').insert({id: 5,
      group_id: 1,
      member_id: 5}),
    knex('group_member').insert({id: 6,
      group_id: 1,
      member_id: 6}),
    knex('group_member').insert({id: 7,
      group_id: 1,
      member_id: 7}),
    knex('group_member').insert({id: 8,
      group_id: 1,
      member_id: 8}),
    knex('group_member').insert({id: 9,
      group_id: 1,
      member_id: 9}),
    knex('group_member').insert({id: 10,
      group_id: 1,
      member_id: 10}),
    knex('group_member').insert({id: 11,
      group_id: 1,
      member_id: 11}),
    knex('group_member').insert({id: 12,
      group_id: 1,
      member_id: 12}),
    knex('group_member').insert({id: 13,
      group_id: 1,
      member_id: 2}),
    knex('group_member').insert({id: 14,
      group_id: 1,
      member_id: 3})
  );
};
